<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sys_user_moss_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->sys_user_moss_id	= 'ID';
		$this->sys_user_moss_agentid	= 'AGENTID';
		$this->sys_user_moss_periode_start	= 'PERIODE_START';
		$this->sys_user_moss_periode_end	= 'PERIODE_END';
		$this->sys_user_moss_shift	= 'SHIFT';
		$this->agentid_id	= 'AGENTID_ID';
		$this->agentid_nmuser	= 'NMUSER';
		$this->agentid_passuser	= 'PASSUSER';
		$this->agentid_opt_level	= 'OPT_LEVEL';
		$this->agentid_opt_status	= 'OPT_STATUS';
		$this->agentid_picture	= 'PICTURE';
		$this->agentid_nama	= 'NAMA';
		$this->agentid_agentid	= 'AGENTID_AGENTID';
		$this->agentid_kategori	= 'KATEGORI';
		$this->agentid_tl	= 'TL';
		$this->agentid_nik_absensi	= 'NIK_ABSENSI';
		$this->shift_id	= 'SHIFT_ID';
		$this->shift_keterangan	= 'KETERANGAN';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_agentid	= 'agentid';
		$this->f_periode_start	= 'periode_start';
		$this->f_periode_end	= 'periode_end';
		$this->f_shift	= 'shift';
		$this->f_agentid_id	= 'agentid_id';
		$this->f_nmuser	= 'nmuser';
		$this->f_passuser	= 'passuser';
		$this->f_opt_level	= 'opt_level';
		$this->f_opt_status	= 'opt_status';
		$this->f_picture	= 'picture';
		$this->f_nama	= 'nama';
		$this->f_agentid_agentid	= 'agentid_agentid';
		$this->f_kategori	= 'kategori';
		$this->f_tl	= 'tl';
		$this->f_nik_absensi	= 'nik_absensi';
		$this->f_shift_id	= 'shift_id';
		$this->f_keterangan	= 'keterangan';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_agentid	=> $this->sys_user_moss_agentid,
			$this->f_periode_start	=> $this->sys_user_moss_periode_start,
			$this->f_periode_end	=> $this->sys_user_moss_periode_end,
			$this->f_keterangan	=> $this->shift_keterangan,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-04-03 12:45:33 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

