<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Qm_score_parameter_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->qm_score_parameter_id	= 'ID';
		$this->qm_score_parameter_urutan	= 'URUTAN';
		$this->qm_score_parameter_keterangan	= 'KETERANGAN';
		$this->qm_score_parameter_bobot	= 'BOBOT';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_urutan	= 'urutan';
		$this->f_keterangan	= 'keterangan';
		$this->f_bobot	= 'bobot';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->qm_score_parameter_id,
			$this->f_urutan	=> $this->qm_score_parameter_urutan,
			$this->f_keterangan	=> $this->qm_score_parameter_keterangan,
			$this->f_bobot	=> $this->qm_score_parameter_bobot,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-07-10 11:06:05 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

