<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_payroll_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->t_payroll_id	= 'ID';
		$this->t_payroll_agentid	= 'AGENTID';
		$this->t_payroll_kehadiran	= 'KEHADIRAN';
		$this->t_payroll_contacted	= 'CONTACTED';
		$this->t_payroll_verified	= 'VERIFIED';
		$this->t_payroll_tenur	= 'TENUR';
		$this->t_payroll_pendidikan	= 'PENDIDIKAN';
		$this->t_payroll_score	= 'SCORE';
		$this->t_payroll_level	= 'LEVEL';
		$this->t_payroll_akomodasi	= 'AKOMODASI';
		$this->t_payroll_t_trasnport	= 'T_TRASNPORT';
		$this->t_payroll_komisi	= 'KOMISI';
		$this->t_payroll_tunj_level	= 'TUNJ_LEVEL';
		$this->t_payroll_tunj_jabatan	= 'TUNJ_JABATAN';
		$this->t_payroll_thp_leveling	= 'THP_LEVELING';
		$this->t_payroll_ot_moss	= 'OT_MOSS';
		$this->t_payroll_other_fee	= 'OTHER_FEE';
		$this->t_payroll_tunj_skill	= 'TUNJ_SKILL';
		$this->t_payroll_perbantuan_hpemail	= 'PERBANTUAN_HPEMAIL';
		$this->t_payroll_perbantuan_hponly	= 'PERBANTUAN_HPONLY';
		$this->t_payroll_nominal_perbantuan	= 'NOMINAL_PERBANTUAN';
		$this->t_payroll_total_thp	= 'TOTAL_THP';
		$this->t_payroll_non_thp	= 'NON_THP';
		$this->t_payroll_benefit_lain	= 'BENEFIT_LAIN';
		$this->t_payroll_m_fee	= 'M_FEE';
		$this->t_payroll_headcount	= 'HEADCOUNT';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_agentid	= 'agentid';
		$this->f_kehadiran	= 'kehadiran';
		$this->f_contacted	= 'contacted';
		$this->f_verified	= 'verified';
		$this->f_tenur	= 'tenur';
		$this->f_pendidikan	= 'pendidikan';
		$this->f_score	= 'score';
		$this->f_level	= 'level';
		$this->f_akomodasi	= 'akomodasi';
		$this->f_t_trasnport	= 't_trasnport';
		$this->f_komisi	= 'komisi';
		$this->f_tunj_level	= 'tunj_level';
		$this->f_tunj_jabatan	= 'tunj_jabatan';
		$this->f_thp_leveling	= 'thp_leveling';
		$this->f_ot_moss	= 'ot_moss';
		$this->f_other_fee	= 'other_fee';
		$this->f_tunj_skill	= 'tunj_skill';
		$this->f_perbantuan_hpemail	= 'perbantuan_hpemail';
		$this->f_perbantuan_hponly	= 'perbantuan_hponly';
		$this->f_nominal_perbantuan	= 'nominal_perbantuan';
		$this->f_total_thp	= 'total_thp';
		$this->f_non_thp	= 'non_thp';
		$this->f_benefit_lain	= 'benefit_lain';
		$this->f_m_fee	= 'm_fee';
		$this->f_headcount	= 'headcount';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->t_payroll_id,
			$this->f_agentid	=> $this->t_payroll_agentid,
			$this->f_kehadiran	=> $this->t_payroll_kehadiran,
			$this->f_contacted	=> $this->t_payroll_contacted,
			$this->f_verified	=> $this->t_payroll_verified,
			$this->f_tenur	=> $this->t_payroll_tenur,
			$this->f_pendidikan	=> $this->t_payroll_pendidikan,
			$this->f_score	=> $this->t_payroll_score,
			$this->f_level	=> $this->t_payroll_level,
			$this->f_akomodasi	=> $this->t_payroll_akomodasi,
			$this->f_t_trasnport	=> $this->t_payroll_t_trasnport,
			$this->f_komisi	=> $this->t_payroll_komisi,
			$this->f_tunj_level	=> $this->t_payroll_tunj_level,
			$this->f_tunj_jabatan	=> $this->t_payroll_tunj_jabatan,
			$this->f_thp_leveling	=> $this->t_payroll_thp_leveling,
			$this->f_ot_moss	=> $this->t_payroll_ot_moss,
			$this->f_other_fee	=> $this->t_payroll_other_fee,
			$this->f_tunj_skill	=> $this->t_payroll_tunj_skill,
			$this->f_perbantuan_hpemail	=> $this->t_payroll_perbantuan_hpemail,
			$this->f_perbantuan_hponly	=> $this->t_payroll_perbantuan_hponly,
			$this->f_nominal_perbantuan	=> $this->t_payroll_nominal_perbantuan,
			$this->f_total_thp	=> $this->t_payroll_total_thp,
			$this->f_non_thp	=> $this->t_payroll_non_thp,
			$this->f_benefit_lain	=> $this->t_payroll_benefit_lain,
			$this->f_m_fee	=> $this->t_payroll_m_fee,
			$this->f_headcount	=> $this->t_payroll_headcount,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-02-02 09:55:54 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

