<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_fraud_alert_check_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->t_fraud_alert_check_id	= 'ID';
		$this->t_fraud_alert_check_no_handphone	= 'NO_HANDPHONE';
		$this->t_fraud_alert_check_tanggal_check	= 'TANGGAL_CHECK';
		$this->t_fraud_alert_check_update_by	= 'UPDATE_BY';
		$this->t_fraud_alert_check_reason	= 'REASON';
		$this->t_fraud_alert_check_status_approve	= 'STATUS_APPROVE';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_no_handphone	= 'no_handphone';
		$this->f_tanggal_check	= 'tanggal_check';
		$this->f_update_by	= 'update_by';
		$this->f_reason	= 'reason';
		$this->f_status_approve	= 'status_approve';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->t_fraud_alert_check_id,
			$this->f_no_handphone	=> $this->t_fraud_alert_check_no_handphone,
			$this->f_tanggal_check	=> $this->t_fraud_alert_check_tanggal_check,
			$this->f_update_by	=> $this->t_fraud_alert_check_update_by,
			$this->f_reason	=> $this->t_fraud_alert_check_reason,
			$this->f_status_approve	=> $this->t_fraud_alert_check_status_approve,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-09-28 13:49:17 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

