<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Trans_digital_channel_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->trans_digital_channel_id	= 'ID';
		$this->trans_digital_channel_digital_channel	= 'DIGITAL_CHANNEL';
		$this->trans_digital_channel_template	= 'TEMPLATE';
		$this->trans_digital_channel_konten_1	= 'KONTEN_1';
		$this->trans_digital_channel_konten_2	= 'KONTEN_2';
		$this->trans_digital_channel_konten_3	= 'KONTEN_3';
		$this->trans_digital_channel_konten_4	= 'KONTEN_4';
		$this->trans_digital_channel_konten_5	= 'KONTEN_5';
		$this->trans_digital_channel_konten	= 'KONTEN';
		$this->trans_digital_channel_distribution	= 'DISTRIBUTION';
		$this->trans_digital_channel_veri_call	= 'VERI_CALL';
		$this->trans_digital_channel_delivery	= 'DELIVERY';
		$this->dc_id	= 'DC_ID';
		$this->dc_channel	= 'CHANNEL';
		$this->dc_template	= 'DC_TEMPLATE';
		$this->dc_konten_1	= 'DC_KONTEN_1';
		$this->dc_konten_2	= 'DC_KONTEN_2';
		$this->dc_konten_3	= 'DC_KONTEN_3';
		$this->dc_konten_4	= 'DC_KONTEN_4';
		$this->dc_konten_5	= 'DC_KONTEN_5';
		$this->dc_status	= 'STATUS';
		$this->dc_last_update	= 'LAST_UPDATE';
		$this->dc_userid	= 'USERID';
		$this->tdc_id	= 'TDC_ID';
		$this->tdc_template	= 'TDC_TEMPLATE';
		$this->tdc_jumlah_konten	= 'JUMLAH_KONTEN';
		$this->tdc_kode_template	= 'KODE_TEMPLATE';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_digital_channel	= 'digital_channel';
		$this->f_template	= 'template';
		$this->f_konten_1	= 'konten_1';
		$this->f_konten_2	= 'konten_2';
		$this->f_konten_3	= 'konten_3';
		$this->f_konten_4	= 'konten_4';
		$this->f_konten_5	= 'konten_5';
		$this->f_konten	= 'konten';
		$this->f_distribution	= 'distribution';
		$this->f_veri_call	= 'veri_call';
		$this->f_delivery	= 'delivery';
		$this->f_dc_id	= 'dc_id';
		$this->f_channel	= 'channel';
		$this->f_dc_template	= 'dc_template';
		$this->f_dc_konten_1	= 'dc_konten_1';
		$this->f_dc_konten_2	= 'dc_konten_2';
		$this->f_dc_konten_3	= 'dc_konten_3';
		$this->f_dc_konten_4	= 'dc_konten_4';
		$this->f_dc_konten_5	= 'dc_konten_5';
		$this->f_status	= 'status';
		$this->f_last_update	= 'last_update';
		$this->f_userid	= 'userid';
		$this->f_tdc_id	= 'tdc_id';
		$this->f_tdc_template	= 'tdc_template';
		$this->f_jumlah_konten	= 'jumlah_konten';
		$this->f_kode_template	= 'kode_template';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->trans_digital_channel_id,
			$this->f_digital_channel	=> $this->trans_digital_channel_digital_channel,
			$this->f_template	=> $this->trans_digital_channel_template,
			$this->f_konten_1	=> $this->trans_digital_channel_konten_1,
			$this->f_konten_2	=> $this->trans_digital_channel_konten_2,
			$this->f_konten_3	=> $this->trans_digital_channel_konten_3,
			$this->f_konten_4	=> $this->trans_digital_channel_konten_4,
			$this->f_konten_5	=> $this->trans_digital_channel_konten_5,
			$this->f_konten	=> $this->trans_digital_channel_konten,
			$this->f_distribution	=> $this->trans_digital_channel_distribution,
			$this->f_veri_call	=> $this->trans_digital_channel_veri_call,
			$this->f_delivery	=> $this->trans_digital_channel_delivery,
			$this->f_dc_id	=> $this->dc_id,
			$this->f_channel	=> $this->dc_channel,
			$this->f_dc_template	=> $this->dc_template,
			$this->f_dc_konten_1	=> $this->dc_konten_1,
			$this->f_dc_konten_2	=> $this->dc_konten_2,
			$this->f_dc_konten_3	=> $this->dc_konten_3,
			$this->f_dc_konten_4	=> $this->dc_konten_4,
			$this->f_dc_konten_5	=> $this->dc_konten_5,
			$this->f_status	=> $this->dc_status,
			$this->f_last_update	=> $this->dc_last_update,
			$this->f_userid	=> $this->dc_userid,
			$this->f_tdc_id	=> $this->tdc_id,
			$this->f_tdc_template	=> $this->tdc_template,
			$this->f_jumlah_konten	=> $this->tdc_jumlah_konten,
			$this->f_kode_template	=> $this->tdc_kode_template,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-12-15 07:56:57 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

