<?php
require APPPATH . '/controllers/Distribution/Distribution_config.php';

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Moss_tvv extends CI_Controller
{
	private $log_key, $log_temp, $title;
	function __construct()
	{
		parent::__construct();
		//  $this->load->model('Custom_model/Dapros_infomedia_model', 'distribution');
		$this->load->model('Custom_model/Dapros_model', 'distribution');
		$this->load->model('Custom_model/Sys_user_table_model', 'sys_user');
		$this->load->model('Custom_model/Trans_profiling_verifikasi_infomedia_model', 'trans_profiling_verifikasi');
		$this->load->model('Custom_model/Trans_profiling_validasi_mos_model', 'trans_profiling_validasi_mos');
		$this->load->model('Custom_model/Trans_profiling_detail_model', 'trans_profiling_detail');
		$this->load->library('session');
		$this->log_key = 'log_Distributon';
		$this->title = new Distribution_config();
	}


	public function index()
	{
		$data = array(
			'title_page_big'		=> 'DATA LIST',
			'title'					=> $this->title,
			'link_create'			=> site_url() . 'Moss_tvv/Moss_tvv/create'
		);

		// Always refresh the token
		$data['token_form'] = substr(md5(uniqid() . microtime() . rand()), 0, 8);
		$_SESSION['token_form'] = $data['token_form'];

		$this->template->load('Moss_tvv/add_form', $data);
	}
	public function edit($id)
	{
		$data = array(
			'title_page_big'		=> 'EDIT DATA',
			'title'					=> $this->title,
			'link_update'			=> site_url() . 'Moss_tvv/Moss_tvv/update_action/' . $id
		);
		$data['data'] = $this->trans_profiling_validasi_mos->get_row(array("idx" => $id));
		$this->template->load('Moss_tvv/edit_form', $data);
	}
	public function create()
	{
		if (
			isset($_POST['token_form']) &&
			isset($_SESSION['token_form']) &&
			$_POST['token_form'] == $_SESSION['token_form']
		) {
			$pstn = $this->input->post('no_pstn');
			if ($this->input->post('no_pstn') == "") {
				$pstn = $this->input->post('no_speedy');
			}
			$data = array(
				'ncli' => $this->input->post('ncli'),
				'no_pstn' => $this->input->post('no_pstn'),
				'no_speedy' => $this->input->post('no_speedy'),
				'no_handpone' => $this->input->post('no_handphone'),
				'email' => $this->input->post('email'),
				// 'nama_pelanggan' => $this->input->post('nama_pelanggan'),
				// 'nama_pastel' => $this->input->post('nama_pelanggan'),
				// 'alamat' => $this->input->post('alamat'),
				'layanan' => 'TVV',
				// 'tagihan' => $this->input->post('tagihan'),
				// 'kecepatan' => $this->input->post('kecepatan'),
				// 'tgl_bayar' => $this->input->post('tgl_bayar'),
				// 'waktu_bayar' => $this->input->post('waktu_bayar'),
				'tgl_insert' => date("Y-m-d H:i:s"),
				'sumber' => "TVV"
			);
			$query = $this->trans_profiling_validasi_mos->add($data);
			if ($query) {
				$status = 1;
			} else {
				$status = 0;
			}
		} else {
			$status = 0;
		}

		redirect(site_url() . 'Moss_tvv/Moss_tvv?success=' . $status);
	}
	public function update_action()
	{
		// $id=$this->input->post("id");
		$pstn = $this->input->post('no_pstn');
		if ($this->input->post('no_pstn') == "") {
			$pstn = $this->input->post('no_speedy');
		}
		$data = array(
			'ncli' => $this->input->post('ncli'),
			'no_pstn' => $this->input->post('no_pstn'),
			'no_speedy' => $this->input->post('no_speedy'),
			'no_handpone' => $this->input->post('no_handphone'),
			'email' => $this->input->post('email'),
			// 'nama_pelanggan' => $this->input->post('nama_pelanggan'),
			// 'nama_pastel' => $this->input->post('nama_pelanggan'),
			// 'alamat' => $this->input->post('alamat'),
			'layanan' => 'TVV',
			// 'tagihan' => $this->input->post('tagihan'),
			// 'kecepatan' => $this->input->post('kecepatan'),
			// 'tgl_bayar' => $this->input->post('tgl_bayar'),
			// 'waktu_bayar' => $this->input->post('waktu_bayar'),
			'tgl_insert' => date("Y-m-d H:i:s"),
			'sumber' => "TVV"
		);
		$query = $this->trans_profiling_validasi_mos->add($data);
		if ($query) {
			$status = 1;
		} else {
			$status = 0;
		}
		redirect(site_url() . 'Moss_tvv/Moss_tvv?success=' . $status);
	}
};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-02-08 07:42:27 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
