<?php


if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Moss extends CI_Controller
{
	private $log_key, $log_temp, $title;
	function __construct()
	{
		parent::__construct();
		$this->load->model('Indibox/Indibox_model', 'tmodel');
		$this->load->model('Custom_model/Sys_user_table_model', 'Sys_user_table_model');
		$this->load->model('Status_call/Status_call_model', 'Status_call_model');
		$this->load->model('sys/Sys_user_log_model', 'log_login');
		$this->load->model('Custom_model/Status_call_model', 'status_call');
	}


	public function index()
	{

		$data['start'] = date('Y-m-d');
		$data['$end'] = date('Y-m-d');
		if (isset($_GET['start']) && isset($_GET['end'])) {
			$data['start'] = $_GET['start'];
			$data['$end'] = $_GET['end'];
		}


		$this->template->load('Moss/Moss_list', $data);
	}

	function get_data_list()
	{

		$data['controller'] = $this;
		$start = date('Y-m-d');
		$end = date('Y-m-d');
		if (isset($_GET['start']) && isset($_GET['end'])) {
			$start = $_GET['start'];
			$end = $_GET['end'];


			$idlogin = $this->session->userdata('idlogin');
			$logindata = $this->log_login->get_by_id($idlogin);

			$userdata = $this->Sys_user_table_model->get_row(array("id" => $logindata->id_user));
			$this->dbtrx = $this->load->database('infomedia');

			// $data['fmoss'] = $this->dbtrx->list_fields('indri_trans_profiling_validasi_mos');
			$data['moss'] = $this->tmodel->live_query("
			SELECT  
			idx, 
			ncli, 
			no_pstn,
			relasi, 
			no_speedy, 
			nama_pelanggan, 
			no_handpone, 
			email, 
			nama_pastel, 
			alamat, 
			kota, 
			regional, 
			update_by, 
			DATE(`lup`)AS TGL_Keluar, 
			TIME(`lup`)AS Jam_Keluar, 
			sumber, 
			DATE(`tgl_insert`)AS TGL_Masuk, 
			TIME(`tgl_insert`)AS Jam_Masuk, 
			TIMEDIFF(`lup`,`tgl_insert`) AS SLG, 
			layanan, 
			reason_call, 
			STATUS, 
			keterangan, 
			(SELECT nama_reason FROM m_reason WHERE idx_reason=reason_call) STATUS 
			FROM indri_trans_profiling_validasi_mos 
			WHERE DATE(`tgl_insert`)  BETWEEN '$start' AND '$end' 
			")->result();
			$data['Status_call_model'] = $this->Status_call_model;
		}
		$this->load->view('Moss/Moss_area', $data);
	}
};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-06-02 15:25:04 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/