<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_log_problem_model extends CI_Model {
   public $id;	
   function __construct(){
        parent::__construct();
   }	
	
	public function json(){
		$this->datatables->select('
			t_log_problem.id as id,
			t_log_problem.tanggal as tanggal,
			t_log_problem.agentid as agentid,
			t_log_problem.kategori_gangguan as kategori_gangguan,
			t_log_problem.solusi as solusi,
			t_log_problem.status as status,
			t_log_problem.keterangan as keterangan,
		');
		
		$this->datatables->from('t_log_problem');

		
		
		//mengembalikan dalam bentuk array
		$q =  json_decode($this->datatables->generate(),true);
		return $q;
	}
	

   public function get_all(){
		$afield = array(
			't_log_problem.id as id',
			't_log_problem.tanggal as tanggal',
			't_log_problem.agentid as agentid',
			't_log_problem.kategori_gangguan as kategori_gangguan',
			't_log_problem.solusi as solusi',
			't_log_problem.status as status',
			't_log_problem.keterangan as keterangan',
		
		);
		$this->db->select($afield);

		$this->db->order_by('t_log_problem.id', 'ASC');
		return $this->db->get('t_log_problem')->result_array();
   }


	public function get_by_id($id){
		$afield = array(
			't_log_problem.id as id',
			't_log_problem.tanggal as tanggal',
			't_log_problem.agentid as agentid',
			't_log_problem.kategori_gangguan as kategori_gangguan',
			't_log_problem.solusi as solusi',
			't_log_problem.status as status',
			't_log_problem.keterangan as keterangan',
		
		);
		$this->db->select($afield);

		$this->db->where('t_log_problem.id', $id);
		$this->db->order_by('t_log_problem.id', 'ASC');
		return $this->db->get('t_log_problem')->row();
   }


	/* Memastikan data yg dibuat tidak kembar/sama,
	   fungsi ini sebagai pengganti fungsi primary key dr db,
	   krn primary key sudah di gunakan untuk column id.
	   -create : id di kosongkan.
	   -update : id di isi dengan id data yg di proses.	
	*/	
	function if_exist($id,$data){
		$this->db->where('t_log_problem.id <>',$id);

		$q = $this->db->get_where('t_log_problem', $data)->result_array();
		
		if(count($q)>0){
			return true;
		}else{
			return false;
		}		

	

	}


	function insert($data){
	
	    /* transaction rollback */
		$this->db->trans_start();
		
		$this->db->insert('t_log_problem', $data);		
		/* id primary yg baru saja di input*/
		$this->id = $this->db->insert_id(); 
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false
	}

	function update($id,$data){

		/* transaction rollback */
		$this->db->trans_start();

		$this->db->where('t_log_problem.id', $id);
		$this->db->update('t_log_problem', $data);
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}

	function delete_multiple($data){
		/* transaction rollback */
		$this->db->trans_start();
		
		if(!empty($data)){
			$this->db->where_in('t_log_problem.id',$data);	
	
			$this->db->delete('t_log_problem');
		}
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
		
	}


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-11-09 08:35:30 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
