<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_pembinaan_nonq_model extends CI_Model {
   public $id;	
   function __construct(){
        parent::__construct();
   }	
	
	public function json(){
		$this->datatables->select('
			t_pembinaan_konseling.id as id,
			t_pembinaan_konseling.nama_konseling as nama_konseling,
			t_pembinaan_konseling.konselor as konselor,
			t_pembinaan_konseling.bulan_tahun as bulan_tahun,
			t_pembinaan_konseling.data_performance as data_performance,
			t_pembinaan_konseling.ketidaksesuaian as ketidaksesuaian,
			t_pembinaan_konseling.jenis_pembinaan as jenis_pembinaan,
			t_pembinaan_konseling.komitmen_perbaikan as komitmen_perbaikan,
		');
		
		$this->datatables->from('t_pembinaan_nonq');

		
		
		//mengembalikan dalam bentuk array
		$q =  json_decode($this->datatables->generate(),true);
		return $q;
	}
	

   public function get_all(){
		$afield = array(
			't_pembinaan_konseling.id as id',
			't_pembinaan_konseling.nama_konseling as nama_konseling',
			't_pembinaan_konseling.konselor as konselor',
			't_pembinaan_konseling.bulan_tahun as bulan_tahun',
			't_pembinaan_konseling.data_performance as data_performance',
			't_pembinaan_konseling.ketidaksesuaian as ketidaksesuaian',
			't_pembinaan_konseling.jenis_pembinaan as jenis_pembinaan',
			't_pembinaan_konseling.komitmen_perbaikan as komitmen_perbaikan',
		
		);
		$this->db->select($afield);

		$this->db->order_by('t_pembinaan_konseling.id', 'ASC');
		return $this->db->get('t_pembinaan_konseling')->result_array();
   }


	public function get_by_id($id){
		$afield = array(
			't_pembinaan_konseling.id as id',
			't_pembinaan_konseling.nama_konseling as nama_konseling',
			't_pembinaan_konseling.konselor as konselor',
			't_pembinaan_konseling.bulan_tahun as bulan_tahun',
			't_pembinaan_konseling.data_performance as data_performance',
			't_pembinaan_konseling.ketidaksesuaian as ketidaksesuaian',
			't_pembinaan_konseling.jenis_pembinaan as jenis_pembinaan',
			't_pembinaan_konseling.komitmen_perbaikan as komitmen_perbaikan',
		
		);
		$this->db->select($afield);

		$this->db->where('t_pembinaan_konseling.id', $id);
		$this->db->order_by('t_pembinaan_konseling.id', 'ASC');
		return $this->db->get('t_pembinaan_konseling')->row();
   }


	/* Memastikan data yg dibuat tidak kembar/sama,
	   fungsi ini sebagai pengganti fungsi primary key dr db,
	   krn primary key sudah di gunakan untuk column id.
	   -create : id di kosongkan.
	   -update : id di isi dengan id data yg di proses.	
	*/	
	function if_exist($id,$data){
		$this->db->where('t_pembinaan_konseling.id <>',$id);

		$q = $this->db->get_where('t_pembinaan_konseling', $data)->result_array();
		
		if(count($q)>0){
			return true;
		}else{
			return false;
		}		

	

	}


	function insert($data){
	
	    /* transaction rollback */
		$this->db->trans_start();
		
		$this->db->insert('t_pembinaan_konseling', $data);		
		/* id primary yg baru saja di input*/
		$this->id = $this->db->insert_id(); 
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false
	}

	function update($id,$data){

		/* transaction rollback */
		$this->db->trans_start();

		$this->db->where('t_pembinaan_konseling.id', $id);
		$this->db->update('t_pembinaan_konseling', $data);
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}

	function delete_multiple($data){
		/* transaction rollback */
		$this->db->trans_start();
		
		if(!empty($data)){
			$this->db->where_in('t_pembinaan_konseling.id',$data);	
	
			$this->db->delete('t_pembinaan_konseling');
		}
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
		
	}


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-03-02 14:02:28 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
