<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_produk_moss_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->t_produk_moss_id	= 'ID';
		$this->t_produk_moss_nama_chanel	= 'NAMA_CHANEL';
		$this->t_produk_moss_kode_chanel	= 'KODE_CHANEL';
		$this->t_produk_moss_harga	= 'HARGA';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_nama_chanel	= 'nama_chanel';
		$this->f_kode_chanel	= 'kode_chanel';
		$this->f_harga	= 'harga';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->t_produk_moss_id,
			$this->f_nama_chanel	=> $this->t_produk_moss_nama_chanel,
			$this->f_kode_chanel	=> $this->t_produk_moss_kode_chanel,
			$this->f_harga	=> $this->t_produk_moss_harga,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-07-30 11:51:31 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

