<?php


if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Moss_coff extends CI_Controller
{
	private $log_key, $log_temp, $title;
	function __construct()
	{
		parent::__construct();
		$this->load->model('Indibox/Indibox_model', 'tmodel');
		$this->load->model('Custom_model/Sys_user_table_model', 'Sys_user_table_model');
		$this->load->model('Status_call/Status_call_model', 'Status_call_model');
		$this->load->model('sys/Sys_user_log_model', 'log_login');
		$this->load->model('Custom_model/Status_call_model', 'status_call');
		$this->infomedia = $this->load->database('infomedia', TRUE);
	}


	public function index()
	{

		$data['start'] = date('Y-m-d');
		if (isset($_GET['start'])) {
			$data['start'] = $_GET['start'];
		}


		$this->template->load('Moss_coff/Moss_list', $data);
	}

	function get_data_list()
	{

		$data['controller'] = $this;
		$start = date('Y-m-d');
		if (isset($_GET['start'])) {
			$start = $_GET['start'];

			$idlogin = $this->session->userdata('idlogin');
			$logindata = $this->log_login->get_by_id($idlogin);

			$userdata = $this->Sys_user_table_model->get_row(array("id" => $logindata->id_user));

			$data['waktu'] = array(
				'00:00-00:30',
				'00:30-01:00',
				'01:00-01:30',
				'01:30-02:00',
				'02:00-02:30',
				'02:30-03:00',
				'03:00-03:30',
				'03:30-04:00',
				'04:00-04:30',
				'04:30-05:00',
				'05:00-05:30',
				'05:30-06:00',
				'06:00-06:30',
				'06:30-07:00',
				'07:00-07:30',
				'07:30-08:00',
				'08:00-08:30',
				'08:30-09:00',
				'09:00-09:30',
				'09:30-10:00',
				'10:00-10:30',
				'10:30-11:00',
				'11:00-11:30',
				'11:30-12:00',
				'12:00-12:30',
				'12:30-13:00',
				'13:00-13:30',
				'13:30-14:00',
				'14:00-14:30',
				'14:30-15:00',
				'15:00-15:30',
				'15:30-16:00',
				'16:00-16:30',
				'16:30-17:00',
				'17:00-17:30',
				'17:30-18:00',
				'18:00-18:30',
				'18:30-19:00',
				'19:00-19:30',
				'19:30-20:00',
				'20:00-20:30',
				'20:30-21:00',
				'21:00-21:30',
				'21:30-22:00',
				'22:00-22:30',
				'22:30-23:00',
				'23:00-23:30',
				'23:30-00:00'
			);

			foreach ($data['waktu'] as $datana) {
				$data['coff']['SLG'][$datana] = '00:00:00';
				$data['coff']['SLFC'][$datana] = '00:00:00';
			}
			$perform = $this->infomedia->query("SELECT concat_ws('-',
			date_format(tgl_insert - interval minute(tgl_insert)%30 minute, '%H:%i'),
			date_format(tgl_insert + interval 30-minute(tgl_insert)%30 minute, '%H:%i')
		) as period,
		COUNT(*) as jml_data,
			  SEC_TO_TIME(AVG(TIMEDIFF(lup, tgl_insert))) as SLG,
			   SEC_TO_TIME(AVG(TIMEDIFF(click_time, tgl_insert))) as SLFC
 FROM indri_trans_profiling_validasi_mos
 WHERE date(tgl_insert)='$start' AND update_by <> 'SYS'
 GROUP BY period
 ORDER BY period ASC;")->result();

			foreach ($perform as $datana) {
				$data['coff']['SLG'][$datana->period] = $datana->SLG;
				$data['coff']['SLFC'][$datana->period] = $datana->SLFC;
				$data['coff']['jml_data'][$datana->period] = $datana->jml_data;
			}
		}
		$this->load->view('Moss_coff/Moss_area', $data);
	}

	// function getslg($date, $jam)

};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-06-02 15:25:04 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/