<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Template_digital_channel_model extends CI_Model {
   public $id;	
   function __construct(){
        parent::__construct();
   }	
	
	public function json(){
		$this->datatables->select('
			template_digital_channel.id as id,
			template_digital_channel.template as template,
			template_digital_channel.jumlah_konten as jumlah_konten,
			template_digital_channel.kode_template as kode_template,
		');
		
		$this->datatables->from('template_digital_channel');

		
		
		//mengembalikan dalam bentuk array
		$q =  json_decode($this->datatables->generate(),true);
		return $q;
	}
	

   public function get_all(){
		$afield = array(
			'template_digital_channel.id as id',
			'template_digital_channel.template as template',
			'template_digital_channel.jumlah_konten as jumlah_konten',
			'template_digital_channel.kode_template as kode_template',
		
		);
		$this->db->select($afield);

		$this->db->order_by('template_digital_channel.id', 'ASC');
		return $this->db->get('template_digital_channel')->result_array();
   }


	public function get_by_id($id){
		$afield = array(
			'template_digital_channel.id as id',
			'template_digital_channel.template as template',
			'template_digital_channel.jumlah_konten as jumlah_konten',
			'template_digital_channel.kode_template as kode_template',
		
		);
		$this->db->select($afield);

		$this->db->where('template_digital_channel.id', $id);
		$this->db->order_by('template_digital_channel.id', 'ASC');
		return $this->db->get('template_digital_channel')->row();
   }


	/* Memastikan data yg dibuat tidak kembar/sama,
	   fungsi ini sebagai pengganti fungsi primary key dr db,
	   krn primary key sudah di gunakan untuk column id.
	   -create : id di kosongkan.
	   -update : id di isi dengan id data yg di proses.	
	*/	
	function if_exist($id,$data){
		$this->db->where('template_digital_channel.id <>',$id);

		$q = $this->db->get_where('template_digital_channel', $data)->result_array();
		
		if(count($q)>0){
			return true;
		}else{
			return false;
		}		

	

	}


	function insert($data){
	
	    /* transaction rollback */
		$this->db->trans_start();
		
		$this->db->insert('template_digital_channel', $data);		
		/* id primary yg baru saja di input*/
		$this->id = $this->db->insert_id(); 
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false
	}

	function update($id,$data){

		/* transaction rollback */
		$this->db->trans_start();

		$this->db->where('template_digital_channel.id', $id);
		$this->db->update('template_digital_channel', $data);
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}

	function delete_multiple($data){
		/* transaction rollback */
		$this->db->trans_start();
		
		if(!empty($data)){
			$this->db->where_in('template_digital_channel.id',$data);	
	
			$this->db->delete('template_digital_channel');
		}
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
		
	}


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-12-15 07:42:06 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
