<?php
require APPPATH . '/controllers/Input_absen/Input_absen_config.php';

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Input_absen_model extends CI_Controller
{
	private $log_key, $log_temp, $title;
	function __construct()
	{
		parent::__construct();
		$this->load->model('Input_absen/Input_absen_model', 'tmodel');
		$this->load->model('Absensi/Absensi_model', 'absensi');
		$this->load->model('Custom_model/Sys_user_table_model', 'sys_user');
		//$this->log_key ='log_Leader_on_duty';
		$this->log_key = 'log_Input_absen';
		$this->title = new Input_absen_config();
	}

	

   public function get_all(){
		$afield = array(
			't_absensi.id as id',
			't_absensi.nik as nik',
			't_absensi.waktu_in as waktu_in',
			't_absensi.stts as stts',
		
		);
		$this->db->select($afield);

		$this->db->order_by('t_absensi.id as id', 'ASC');
		return $this->db->get('t_absensi')->result_array();
   }


	public function get_by_id($id){
		$afield = array(
			't_absensi.id as id',
			't_absensi.nik as nik',
			't_absensi.waktu_in as waktu_in',
			't_absensi.stts as stts',
		
		);
		$this->db->select($afield);

		$this->db->where('t_absensi.id', $id);
		$this->db->order_by('t_absensi.id', 'ASC');
		return $this->db->get('t_absensi')->row();
   }


	/* Memastikan data yg dibuat tidak kembar/sama,
	   fungsi ini sebagai pengganti fungsi primary key dr db,
	   krn primary key sudah di gunakan untuk column id.
	   -create : id di kosongkan.
	   -update : id di isi dengan id data yg di proses.	
	*/	
	function if_exist($id,$data){
		$this->db->where('t_absensi.id <>',$id);

		$q = $this->db->get_where('t_absensi', $data)->result_array();
		
		if(count($q)>0){
			return true;
		}else{
			return false;
		}		

	

	}


	function insert($data){
	
	    /* transaction rollback */
		$this->db->trans_start();
		
		$this->db->insert('t_absensi', $data);		
		/* id primary yg baru saja di input*/
		$this->id = $this->db->insert_id(); 
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false
	}

	function update($id,$data){

		/* transaction rollback */
		$this->db->trans_start();

		$this->db->where('t_absensi.id', $id);
		$this->db->update('t_absensi', $data);
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}

	function delete_multiple($data){
		/* transaction rollback */
		$this->db->trans_start();
		
		if(!empty($data)){
			$this->db->where_in('t_absensi.id',$data);	
	
			$this->db->delete('t_absensi');
		}
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
		
	}


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-01-31 15:28:46 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
