<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_pembinaan_batl_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->t_pembinaan_batl_id	= 'ID';
		$this->t_pembinaan_batl_penerima_teguran	= 'PENERIMA_TEGURAN';
		$this->t_pembinaan_batl_pemberi_teguran	= 'PEMBERI_TEGURAN';
		$this->t_pembinaan_batl_tanggal_teguran	= 'TANGGAL_TEGURAN';
		$this->t_pembinaan_batl_isi_teguran_lisan	= 'ISI_TEGURAN_LISAN';
		$this->t_pembinaan_batl_pertimbangan_tindakan	= 'PERTIMBANGAN_TINDAKAN';
		$this->t_pembinaan_batl_komitmen	= 'KOMITMEN';
		$this->t_pembinaan_batl_verifikasi	= 'VERIFIKASI';
		$this->t_pembinaan_batl_evidance	= 'EVIDANCE';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_penerima_teguran	= 'penerima_teguran';
		$this->f_pemberi_teguran	= 'pemberi_teguran';
		$this->f_tanggal_teguran	= 'tanggal_teguran';
		$this->f_isi_teguran_lisan	= 'isi_teguran_lisan';
		$this->f_pertimbangan_tindakan	= 'pertimbangan_tindakan';
		$this->f_komitmen	= 'komitmen';
		$this->f_verifikasi	= 'verifikasi';
		$this->f_evidance	= 'evidance';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->t_pembinaan_batl_id,
			$this->f_penerima_teguran	=> $this->t_pembinaan_batl_penerima_teguran,
			$this->f_pemberi_teguran	=> $this->t_pembinaan_batl_pemberi_teguran,
			$this->f_tanggal_teguran	=> $this->t_pembinaan_batl_tanggal_teguran,
			$this->f_isi_teguran_lisan	=> $this->t_pembinaan_batl_isi_teguran_lisan,
			$this->f_pertimbangan_tindakan	=> $this->t_pembinaan_batl_pertimbangan_tindakan,
			$this->f_komitmen	=> $this->t_pembinaan_batl_komitmen,
			$this->f_verifikasi	=> $this->t_pembinaan_batl_verifikasi,
			$this->f_evidance	=> $this->t_pembinaan_batl_evidance,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-03-01 09:07:06 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

