<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_fraud_alert_check_model extends CI_Model {
   public $id;	
   function __construct(){
        parent::__construct();
   }	
	
	public function json(){
		$this->datatables->select('
			t_fraud_alert_check.id as id,
			t_fraud_alert_check.no_handphone as no_handphone,
			t_fraud_alert_check.tanggal_check as tanggal_check,
			t_fraud_alert_check.update_by as update_by,
			t_fraud_alert_check.reason as reason,
			t_fraud_alert_check.status_approve as status_approve,
		');
		
		$this->datatables->from('t_fraud_alert_check');

		
		
		//mengembalikan dalam bentuk array
		$q =  json_decode($this->datatables->generate(),true);
		return $q;
	}
	

   public function get_all(){
		$afield = array(
			't_fraud_alert_check.id as id',
			't_fraud_alert_check.no_handphone as no_handphone',
			't_fraud_alert_check.tanggal_check as tanggal_check',
			't_fraud_alert_check.update_by as update_by',
			't_fraud_alert_check.reason as reason',
			't_fraud_alert_check.status_approve as status_approve',
		
		);
		$this->db->select($afield);

		$this->db->order_by('t_fraud_alert_check.id', 'ASC');
		return $this->db->get('t_fraud_alert_check')->result_array();
   }


	public function get_by_id($id){
		$afield = array(
			't_fraud_alert_check.id as id',
			't_fraud_alert_check.no_handphone as no_handphone',
			't_fraud_alert_check.tanggal_check as tanggal_check',
			't_fraud_alert_check.update_by as update_by',
			't_fraud_alert_check.reason as reason',
			't_fraud_alert_check.status_approve as status_approve',
		
		);
		$this->db->select($afield);

		$this->db->where('t_fraud_alert_check.id', $id);
		$this->db->order_by('t_fraud_alert_check.id', 'ASC');
		return $this->db->get('t_fraud_alert_check')->row();
   }


	/* Memastikan data yg dibuat tidak kembar/sama,
	   fungsi ini sebagai pengganti fungsi primary key dr db,
	   krn primary key sudah di gunakan untuk column id.
	   -create : id di kosongkan.
	   -update : id di isi dengan id data yg di proses.	
	*/	
	function if_exist($id,$data){
		$this->db->where('t_fraud_alert_check.id <>',$id);

		$q = $this->db->get_where('t_fraud_alert_check', $data)->result_array();
		
		if(count($q)>0){
			return true;
		}else{
			return false;
		}		

	

	}


	function insert($data){
	
	    /* transaction rollback */
		$this->db->trans_start();
		
		$this->db->insert('t_fraud_alert_check', $data);		
		/* id primary yg baru saja di input*/
		$this->id = $this->db->insert_id(); 
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false
	}

	function update($id,$data){

		/* transaction rollback */
		$this->db->trans_start();

		$this->db->where('t_fraud_alert_check.id', $id);
		$this->db->update('t_fraud_alert_check', $data);
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}

	function delete_multiple($data){
		/* transaction rollback */
		$this->db->trans_start();
		
		if(!empty($data)){
			$this->db->where_in('t_fraud_alert_check.id',$data);	
	
			$this->db->delete('t_fraud_alert_check');
		}
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
		
	}


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-09-28 13:49:17 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
