<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_performance_agent_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->t_performance_agent_id	= 'ID';
		$this->t_performance_agent_agentid	= 'AGENTID';
		$this->t_performance_agent_bulan	= 'BULAN';
		$this->t_performance_agent_contactedr	= 'CONTACTED_REG';
		$this->t_performance_agent_verifiedr	= 'VERIFIED_REG';
		$this->t_performance_agent_hpemailr	= 'HPEMAIL_REG';
		$this->t_performance_agent_hpr	= 'HP_REG';
		$this->t_performance_agent_contactedm	= 'CONTACTED_MOSS';
		$this->t_performance_agent_verifiedm	= 'VERIFIED_MOSS';
		$this->t_performance_agent_hpemailm	= 'HPEMAIL_MOSS';
		$this->t_performance_agent_hpm	= 'HP_MOSS';
		$this->t_performance_agent_hadir	= 'HADIR';
		$this->t_performance_agent_telat	= 'TELAT';
		$this->t_performance_agent_absen	= 'ABSEN';
		$this->t_performance_agent_sakit	= 'SAKIT';
		$this->t_performance_agent_izin	= 'IZIN';
		$this->t_performance_agent_payrol	= 'PAYROL';
		$this->agentid_id	= 'AGENTID_ID';
		$this->agentid_nmuser	= 'NMUSER';
		$this->agentid_passuser	= 'PASSUSER';
		$this->agentid_opt_level	= 'OPT_LEVEL';
		$this->agentid_opt_status	= 'OPT_STATUS';
		$this->agentid_picture	= 'PICTURE';
		$this->agentid_nama	= 'NAMA';
		$this->agentid_agentid	= 'AGENTID_AGENTID';
		$this->agentid_kategori	= 'KATEGORI';
		$this->agentid_tl	= 'TL';
		$this->agentid_nik_absensi	= 'NIK_ABSENSI';
		$this->agentid_agentid_mos	= 'AGENTID_MOS';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_agentid	= 'agentid';
		$this->f_bulan	= 'bulan';
		$this->f_contactedr	= 'contactedr';
		$this->f_verifiedr	= 'verifiedr';
		$this->f_hpemailr	= 'hpemailr';
		$this->f_hpr	= 'hpr';
		$this->f_contactedm	= 'contactedm';
		$this->f_verifiedm	= 'verifiedm';
		$this->f_hpemailm	= 'hpemailm';
		$this->f_hpm	= 'hpm';
		$this->f_hadir	= 'hadir';
		$this->f_telat	= 'telat';
		$this->f_absen	= 'absen';
		$this->f_sakit	= 'sakit';
		$this->f_izin	= 'izin';
		$this->f_payrol	= 'payrol';
		$this->f_agentid_id	= 'agentid_id';
		$this->f_nmuser	= 'nmuser';
		$this->f_passuser	= 'passuser';
		$this->f_opt_level	= 'opt_level';
		$this->f_opt_status	= 'opt_status';
		$this->f_picture	= 'picture';
		$this->f_nama	= 'nama';
		$this->f_agentid_agentid	= 'agentid_agentid';
		$this->f_kategori	= 'kategori';
		$this->f_tl	= 'tl';
		$this->f_nik_absensi	= 'nik_absensi';
		$this->f_agentid_mos	= 'agentid_mos';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->t_performance_agent_id,
			$this->f_agentid	=> $this->t_performance_agent_agentid,
			$this->f_bulan	=> $this->t_performance_agent_bulan,
			$this->f_contactedr	=> $this->t_performance_agent_contactedr,
			$this->f_verifiedr	=> $this->t_performance_agent_verifiedr,
			$this->f_hpemailr	=> $this->t_performance_agent_hpemailr,
			$this->f_hpr	=> $this->t_performance_agent_hpr,
			$this->f_contactedm	=> $this->t_performance_agent_contactedm,
			$this->f_verifiedm	=> $this->t_performance_agent_verifiedm,
			$this->f_hpemailm	=> $this->t_performance_agent_hpemailm,
			$this->f_hpm	=> $this->t_performance_agent_hpm,
			$this->f_hadir	=> $this->t_performance_agent_hadir,
			$this->f_telat	=> $this->t_performance_agent_telat,
			$this->f_absen	=> $this->t_performance_agent_absen,
			$this->f_sakit	=> $this->t_performance_agent_sakit,
			$this->f_izin	=> $this->t_performance_agent_izin,
			$this->f_payrol	=> $this->t_performance_agent_payrol,
			$this->f_agentid_id	=> $this->agentid_id,
			$this->f_nmuser	=> $this->agentid_nmuser,
			$this->f_passuser	=> $this->agentid_passuser,
			$this->f_opt_level	=> $this->agentid_opt_level,
			$this->f_opt_status	=> $this->agentid_opt_status,
			$this->f_picture	=> $this->agentid_picture,
			$this->f_nama	=> $this->agentid_nama,
			$this->f_agentid_agentid	=> $this->agentid_agentid,
			$this->f_kategori	=> $this->agentid_kategori,
			$this->f_tl	=> $this->agentid_tl,
			$this->f_nik_absensi	=> $this->agentid_nik_absensi,
			$this->f_agentid_mos	=> $this->agentid_agentid_mos,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-11-02 14:23:06 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

