<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_pembinaan_batl_model extends CI_Model {
   public $id;	
   function __construct(){
        parent::__construct();
   }	
	
	public function json(){
		$this->datatables->select('
			t_pembinaan_batl.id as id,
			t_pembinaan_batl.penerima_teguran as penerima_teguran,
			t_pembinaan_batl.pemberi_teguran as pemberi_teguran,
			t_pembinaan_batl.tanggal_teguran as tanggal_teguran,
			t_pembinaan_batl.isi_teguran_lisan as isi_teguran_lisan,
			t_pembinaan_batl.pertimbangan_tindakan as pertimbangan_tindakan,
			t_pembinaan_batl.komitmen as komitmen,
			t_pembinaan_batl.verifikasi as verifikasi,
			t_pembinaan_batl.evidance as evidance,
		');
		
		$this->datatables->from('t_pembinaan_batl');

		
		
		//mengembalikan dalam bentuk array
		$q =  json_decode($this->datatables->generate(),true);
		return $q;
	}
	

   public function get_all(){
		$afield = array(
			't_pembinaan_batl.id as id',
			't_pembinaan_batl.penerima_teguran as penerima_teguran',
			't_pembinaan_batl.pemberi_teguran as pemberi_teguran',
			't_pembinaan_batl.tanggal_teguran as tanggal_teguran',
			't_pembinaan_batl.isi_teguran_lisan as isi_teguran_lisan',
			't_pembinaan_batl.pertimbangan_tindakan as pertimbangan_tindakan',
			't_pembinaan_batl.komitmen as komitmen',
			't_pembinaan_batl.verifikasi as verifikasi',
			't_pembinaan_batl.evidance as evidance',
		
		);
		$this->db->select($afield);

		$this->db->order_by('t_pembinaan_batl.id', 'ASC');
		return $this->db->get('t_pembinaan_batl')->result_array();
   }


	public function get_by_id($id){
		$afield = array(
			't_pembinaan_batl.id as id',
			't_pembinaan_batl.penerima_teguran as penerima_teguran',
			't_pembinaan_batl.pemberi_teguran as pemberi_teguran',
			't_pembinaan_batl.tanggal_teguran as tanggal_teguran',
			't_pembinaan_batl.isi_teguran_lisan as isi_teguran_lisan',
			't_pembinaan_batl.pertimbangan_tindakan as pertimbangan_tindakan',
			't_pembinaan_batl.komitmen as komitmen',
			't_pembinaan_batl.verifikasi as verifikasi',
			't_pembinaan_batl.evidance as evidance',
		
		);
		$this->db->select($afield);

		$this->db->where('t_pembinaan_batl.id', $id);
		$this->db->order_by('t_pembinaan_batl.id', 'ASC');
		return $this->db->get('t_pembinaan_batl')->row();
   }


	/* Memastikan data yg dibuat tidak kembar/sama,
	   fungsi ini sebagai pengganti fungsi primary key dr db,
	   krn primary key sudah di gunakan untuk column id.
	   -create : id di kosongkan.
	   -update : id di isi dengan id data yg di proses.	
	*/	
	function if_exist($id,$data){
		$this->db->where('t_pembinaan_batl.id <>',$id);

		$q = $this->db->get_where('t_pembinaan_batl', $data)->result_array();
		
		if(count($q)>0){
			return true;
		}else{
			return false;
		}		

	

	}


	function insert($data){
	
	    /* transaction rollback */
		$this->db->trans_start();
		
		$this->db->insert('t_pembinaan_batl', $data);		
		/* id primary yg baru saja di input*/
		$this->id = $this->db->insert_id(); 
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false
	}

	function update($id,$data){

		/* transaction rollback */
		$this->db->trans_start();

		$this->db->where('t_pembinaan_batl.id', $id);
		$this->db->update('t_pembinaan_batl', $data);
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}

	function delete_multiple($data){
		/* transaction rollback */
		$this->db->trans_start();
		
		if(!empty($data)){
			$this->db->where_in('t_pembinaan_batl.id',$data);	
	
			$this->db->delete('t_pembinaan_batl');
		}
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
		
	}


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-03-01 09:07:06 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
