<?php
require APPPATH . '/controllers/Histori_call/Histori_call_config.php';

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Histori_call_tvv extends CI_Controller
{
	private $log_key, $log_temp, $title;
	function __construct()
	{
		parent::__construct();
		$this->load->model('Indibox/Indibox_model', 'tmodel');
		$this->load->model('Custom_model/Sys_user_table_model', 'Sys_user_table_model');
		$this->load->model('Custom_model/Status_call_model', 'Status_call');
		$this->load->model('Custom_model/Trans_profiling_verifikasi_infomedia_model', 'verifikasi');
		$this->load->model('Custom_model/Sys_user_table_model', 'sys_user');
		$this->load->model('sys/Sys_user_log_model', 'log_login');
		$this->load->model('Custom_model/Trans_profiling_last_month_infomedia_model', 'trans_profiling_last_month');
		$this->load->model('Custom_model/Trans_profiling_validasi_mos_model', 'trans_profiling_validasi_mos');

		$this->log_key = 'log_Indibox';
		$this->title = new Histori_call_config();
	}


	public function index()
	{
		$this->load->model('sys/Sys_user_log_model', 'log_login');
		$this->load->model('Custom_model/Sys_user_table_model', 'Sys_user_table_model');
		$idlogin = $this->session->userdata('idlogin');
		$logindata = $this->log_login->get_by_id($idlogin);

		$userdata = $this->Sys_user_table_model->get_row(array("id" => $logindata->id_user));

		$data = array(
			'title_page_big'		=> 'Call History',
			'title'					=> $this->title,
		);
		$data['controller'] = $this;
		$tgl = $this->input->get('tgl');
		if (isset($tgl)) {
			//$tgl = date('Y-m-d');
			$data['list'] = $this->trans_profiling_validasi_mos->live_query('
		SELECT * FROM trans_profiling_validasi_mos WHERE DATE(lup)="' . $tgl . '" AND update_by IS NOT NULL AND sumber="TVV"
		')->result_array();
		} else {
			$no = 0;
			$data['list_outbound'] = $this->tmodel->live_query("SELECT DISTINCT ncli,no_pstn,no_speedy,nama_pastel,no_handpone,email,layanan FROM
			trans_profiling_validasi_mos WHERE `status` IN ('0','3',null) and ncli IS NOT NULL AND update_by is null  AND sumber = 'TVV' order by tgl_insert desc")->result_array();
			$data_list = array();

			foreach ($data['list_outbound'] as $datanya) {
				$no++;
				$nom = 0;
				$data_list[$no] = $datanya;
				$ncli = $datanya['ncli'];
				$no_pstn = $datanya['no_pstn'];
				$cekdouble = $this->tmodel->live_query("SELECT idx as countData,tgl_insert FROM
				trans_profiling_validasi_mos WHERE `status` IN ('0','3',null) AND update_by is null AND ncli='$ncli' AND no_pstn='$no_pstn' AND sumber = 'TVV'")->result();
				foreach ($cekdouble as $datadouble) {

					$data_list[$no]['idx'] = $datadouble->countData;
					// echo $datadouble->tgl_insert;
					$tgl_insert = $datadouble->tgl_insert;
					$data_list[$no]['lup'] = $tgl_insert;
				}
			}
			$data['data_list'] = $data_list;
		}
		// $tgl='2020-07-07';
		$data['user_categori'] = $userdata->opt_level;
		// if ($data['user_categori'] == '14') {

		// }


		$this->template->load('Moss_tvv/Histori_call_list', $data);
	}

	public function detail($id)
	{
		// $detail = $this->tmodel->live_query('
		// SELECT * FROM trans_profiling WHERE idx="' . $id . '" 
		// ')->row();
		// $num = $this->verifikasi->get_count(array("ncli" => $detail->ncli));
		// if ($num > 0) {
		// 	echo "data sudah diverifikasi";
		// } else {
		// 	redirect('http://10.194.194.61/profilling/app/form_outbound.php?phone=' . $detail->pstn1 . '&ncli=' . $detail->ncli);
		// }
	}

	public function refresh_table($token)
	{
		if ($token == $this->_token) {
			$row = $this->tmodel->json();

			//encode id 
			$tm = time();
			$this->session->set_userdata($this->log_key, $tm);
			$x = 0;
			foreach ($row['data'] as $val) {
				$idgenerate = _encode_id($val['id'], $tm);
				$row['data'][$x]['id'] = $idgenerate;
				$x++;
			}

			$o = new Outputview();
			$o->success	= 'true';
			$o->serverside	= 'true';
			$o->message	= $row;

			echo $o->result();
		} else {
			redirect('Auth');
		}
	}
};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-06-02 15:25:04 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
