<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class T_news_config
{



	function __construct()
	{
		/* title */
		$this->general		= new General_title();
		$this->t_news_id	= 'ID';
		$this->t_news_id_sender	= 'Sender';
		$this->t_news_optlevel_receiver	= 'Receiver';
		$this->t_news_title	= 'TITLE';
		$this->t_news_kategori_news	= 'News Category';
		$this->t_news_isi_berita	= 'Content';
		$this->t_news_tanggal_publish	= 'Date Publish';
		$this->t_news_status_publish	= 'Publish Status';
		/*$this->nmuser_id	= 'NMUSER_ID';
		$this->nmuser_nmuser	= 'NMUSER';
		$this->nmuser_passuser	= 'PASSUSER';
		$this->nmuser_opt_level	= 'OPT_LEVEL';
		$this->nmuser_opt_status	= 'OPT_STATUS';
		$this->nmuser_picture	= 'PICTURE';
		$this->nmuser_nama	= 'NAMA';
		$this->nmuser_agentid	= 'AGENTID';
		$this->nmuser_kategori	= 'KATEGORI';
		$this->nmuser_tl	= 'TL';
		$this->nmuser_nik_absensi	= 'NIK_ABSENSI';
		$this->optlvl_id	= 'OPTLVL_ID';
		$this->optlvl_nmuser	= 'OPTLVL_NMUSER';
		$this->optlvl_passuser	= 'OPTLVL_PASSUSER';
		$this->optlvl_opt_level	= 'OPTLVL_OPT_LEVEL';
		$this->optlvl_opt_status	= 'OPTLVL_OPT_STATUS';
		$this->optlvl_picture	= 'OPTLVL_PICTURE';
		$this->optlvl_nama	= 'OPTLVL_NAMA';
		$this->optlvl_agentid	= 'OPTLVL_AGENTID';
		$this->optlvl_kategori	= 'OPTLVL_KATEGORI';
		$this->optlvl_tl	= 'OPTLVL_TL';
		$this->optlvl_nik_absensi	= 'OPTLVL_NIK_ABSENSI';
		*/




		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_id_sender	= 'id_sender';
		$this->f_optlevel_receiver	= 'optlevel_receiver';
		$this->f_title	= 'title';
		$this->f_kategori_news	= 'kategori_news';
		$this->f_isi_berita	= 'isi_berita';
		$this->f_tanggal_publish	= 'tanggal_publish';
		$this->f_status_publish	= 'status_publish';
		$this->f_nmuser_id	= 'nmuser_id';
		$this->f_nmuser	= 'nmuser';
		$this->f_passuser	= 'passuser';
		$this->f_opt_level	= 'opt_level';
		$this->f_opt_status	= 'opt_status';
		$this->f_picture	= 'picture';
		$this->f_nama	= 'nama';
		$this->f_agentid	= 'agentid';
		$this->f_kategori	= 'kategori';
		$this->f_tl	= 'tl';
		$this->f_nik_absensi	= 'nik_absensi';
		$this->f_optlvl_id	= 'optlvl_id';
		$this->f_optlvl_nmuser	= 'optlvl_nmuser';
		$this->f_optlvl_passuser	= 'optlvl_passuser';
		$this->f_optlvl_opt_level	= 'optlvl_opt_level';
		$this->f_optlvl_opt_status	= 'optlvl_opt_status';
		$this->f_optlvl_picture	= 'optlvl_picture';
		$this->f_optlvl_nama	= 'optlvl_nama';
		$this->f_optlvl_agentid	= 'optlvl_agentid';
		$this->f_optlvl_kategori	= 'optlvl_kategori';
		$this->f_optlvl_tl	= 'optlvl_tl';
		$this->f_optlvl_nik_absensi	= 'optlvl_nik_absensi';




		/* CONFIG FORM LIST */
		/* field_alias_database => $title */
	/*	$receiver = $this->f_opt_level;
		if ($receiver == 8) {

			$optlevel = "Agent";
		} else if ($receiver == 9) {
			$optlevel = "Team Leader";
		} else {
			$optlevel = "Administrator";
		}
		*/
		
		
		$this->table_column = array(
			$this->f_id	=> $this->t_news_id,
			$this->f_nmuser	=> $this->t_news_id_sender,
			$this->f_optlevel_receiver => $this->t_news_optlevel_receiver,
			$this->f_title	=> $this->t_news_title,
			$this->f_kategori_news	=> $this->t_news_kategori_news,
			$this->f_isi_berita	=> $this->t_news_isi_berita,
			$this->f_tanggal_publish	=> $this->t_news_tanggal_publish,
			$this->f_status_publish	=> $this->t_news_status_publish,
			/*	$this->f_nmuser_id	=> $this->nmuser_id,
			$this->f_nmuser	=> $this->nmuser_nmuser,
			$this->f_passuser	=> $this->nmuser_passuser,
			$this->f_opt_level	=> $this->nmuser_opt_level,
			$this->f_opt_status	=> $this->nmuser_opt_status,
			$this->f_picture	=> $this->nmuser_picture,
			$this->f_nama	=> $this->nmuser_nama,
			$this->f_agentid	=> $this->nmuser_agentid,
			$this->f_kategori	=> $this->nmuser_kategori,
			$this->f_tl	=> $this->nmuser_tl,
			$this->f_nik_absensi	=> $this->nmuser_nik_absensi,
			$this->f_optlvl_id	=> $this->optlvl_id,
			$this->f_optlvl_nmuser	=> $this->optlvl_nmuser,
			$this->f_optlvl_passuser	=> $this->optlvl_passuser,
			$this->f_optlvl_opt_level	=> $this->optlvl_opt_level,
			$this->f_optlvl_opt_status	=> $this->optlvl_opt_status,
			$this->f_optlvl_picture	=> $this->optlvl_picture,
			$this->f_optlvl_nama	=> $this->optlvl_nama,
			$this->f_optlvl_agentid	=> $this->optlvl_agentid,
			$this->f_optlvl_kategori	=> $this->optlvl_kategori,
			$this->f_optlvl_tl	=> $this->optlvl_tl,
			$this->f_optlvl_nik_absensi	=> $this->optlvl_nik_absensi, */
		);
	}
};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-03-31 12:57:58 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
