<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_pembinaan_model extends CI_Model {
   public $id;	
   function __construct(){
        parent::__construct();
   }	
	
	public function json(){
		$this->datatables->select('
			t_pembinaan.id as id,
			t_pembinaan.id_kasus as id_kasus,
			t_pembinaan.tingkat_pembinaan as tingkat_pembinaan,
			t_pembinaan.tanggal_pembinaan as tanggal_pembinaan,
			t_pembinaan.penyuluhan as penyuluhan,
			t_pembinaan.keterangan as keterangan,
			t_pembinaan.agentid as agentid,
			t_pembinaan.action_plan as action_plan,
			t_pembinaan.input_by as input_by,
			t_pembinaan.hasil as hasil,
			t_pembinaan.jenis as jenis,
		');
		
		$this->datatables->from('t_pembinaan');

		
		
		//mengembalikan dalam bentuk array
		$q =  json_decode($this->datatables->generate(),true);
		return $q;
	}
	

   public function get_all(){
		$afield = array(
			't_pembinaan.id as id',
			't_pembinaan.id_kasus as id_kasus',
			't_pembinaan.tingkat_pembinaan as tingkat_pembinaan',
			't_pembinaan.tanggal_pembinaan as tanggal_pembinaan',
			't_pembinaan.penyuluhan as penyuluhan',
			't_pembinaan.keterangan as keterangan',
			't_pembinaan.agentid as agentid',
			't_pembinaan.action_plan as action_plan',
			't_pembinaan.input_by as input_by',
			't_pembinaan.hasil as hasil',
			't_pembinaan.jenis as jenis',
		
		);
		$this->db->select($afield);

		$this->db->order_by('t_pembinaan.id', 'ASC');
		return $this->db->get('t_pembinaan')->result_array();
   }


	public function get_by_id($id){
		$afield = array(
			't_pembinaan.id as id',
			't_pembinaan.id_kasus as id_kasus',
			't_pembinaan.tingkat_pembinaan as tingkat_pembinaan',
			't_pembinaan.tanggal_pembinaan as tanggal_pembinaan',
			't_pembinaan.penyuluhan as penyuluhan',
			't_pembinaan.keterangan as keterangan',
			't_pembinaan.agentid as agentid',
			't_pembinaan.action_plan as action_plan',
			't_pembinaan.input_by as input_by',
			't_pembinaan.hasil as hasil',
			't_pembinaan.jenis as jenis',
		
		);
		$this->db->select($afield);

		$this->db->where('t_pembinaan.id', $id);
		$this->db->order_by('t_pembinaan.id', 'ASC');
		return $this->db->get('t_pembinaan')->row();
   }


	/* Memastikan data yg dibuat tidak kembar/sama,
	   fungsi ini sebagai pengganti fungsi primary key dr db,
	   krn primary key sudah di gunakan untuk column id.
	   -create : id di kosongkan.
	   -update : id di isi dengan id data yg di proses.	
	*/	
	function if_exist($id,$data){
		$this->db->where('t_pembinaan.id <>',$id);

		$q = $this->db->get_where('t_pembinaan', $data)->result_array();
		
		if(count($q)>0){
			return true;
		}else{
			return false;
		}		

	

	}


	function insert($data){
	
	    /* transaction rollback */
		$this->db->trans_start();
		
		$this->db->insert('t_pembinaan', $data);		
		/* id primary yg baru saja di input*/
		$this->id = $this->db->insert_id(); 
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false
	}

	function update($id,$data){

		/* transaction rollback */
		$this->db->trans_start();

		$this->db->where('t_pembinaan.id', $id);
		$this->db->update('t_pembinaan', $data);
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}

	function delete_multiple($data){
		/* transaction rollback */
		$this->db->trans_start();
		
		if(!empty($data)){
			$this->db->where_in('t_pembinaan.id',$data);	
	
			$this->db->delete('t_pembinaan');
		}
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
		
	}


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-11-23 15:22:32 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
