<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_pembinaan_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->t_pembinaan_id	= 'ID';
		$this->t_pembinaan_id_kasus	= 'ID_KASUS';
		$this->t_pembinaan_tanggal_pembinaan	= 'TANGGAL_PEMBINAAN';
		$this->t_pembinaan_tingkat_pembinaan	= 'TINGKAT_PEMBINAAN';
		$this->t_pembinaan_keterangan	= 'KETERANGAN';		
		$this->t_pembinaan_agentid	= 'AGENTID';
		$this->t_pembinaan_input_by	= 'INPUT_BY';

		$this->t_pembinaan_hasil	= 'HASIL';
		$this->t_pembinaan_jenis	= 'JENIS';		
		$this->t_pembinaan_penyuluhan	= 'PENYULUHAN';	
		$this->t_pembinaan_action_plan	= 'ACTION_PLAN';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_id_kasus	= 'id_kasus';
		$this->f_tanggal_pembinaan	= 'tanggal_pembinaan';
		$this->f_tingkat_pembinaan	= 'tingkat_pembinaan';		
		$this->f_keterangan	= 'keterangan';
		$this->f_agentid	= 'agentid';
		$this->f_input_by	= 'input_by';
		$this->f_hasil	= 'hasil';
		$this->f_jenis	= 'jenis';
		$this->f_action_plan	= 'action_plan';
		$this->f_penyuluhan	= 'penyuluhan';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->t_pembinaan_id,
			$this->f_id_kasus	=> $this->t_pembinaan_id_kasus,
			$this->f_tingkat_pembinaan	=> $this->t_pembinaan_tingkat_pembinaan,
			$this->f_tanggal_pembinaan	=> $this->t_pembinaan_tanggal_pembinaan,
			// $this->f_penyuluhan	=> $this->t_pembinaan_penyuluhan,
			$this->f_keterangan	=> $this->t_pembinaan_keterangan,
			$this->f_agentid	=> $this->t_pembinaan_agentid,
			// $this->f_action_plan	=> $this->t_pembinaan_action_plan,
			$this->f_input_by	=> $this->t_pembinaan_input_by,
			// $this->f_hasil	=> $this->t_pembinaan_hasil,
			$this->f_jenis	=> $this->t_pembinaan_jenis,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-11-23 15:22:32 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

