<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sys_user_detail_payroll_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->sys_user_detail_payroll_id	= 'ID';
		$this->sys_user_detail_payroll_agentid	= 'AGENTID';
		$this->sys_user_detail_payroll_bulan	= 'BULAN';
		$this->sys_user_detail_payroll_hk	= 'HK';
		$this->sys_user_detail_payroll_kehadiran	= 'KEHADIRAN';
		$this->sys_user_detail_payroll_contacted	= 'CONTACTED';
		$this->sys_user_detail_payroll_verified	= 'VERIFIED';
		$this->sys_user_detail_payroll_reward	= 'REWARD';
		$this->sys_user_detail_payroll_pendidikan	= 'PENDIDIKAN';
		$this->sys_user_detail_payroll_foreign	= 'FOREIGN';
		$this->sys_user_detail_payroll_score	= 'SCORE';
		$this->sys_user_detail_payroll_level	= 'LEVEL';
		$this->sys_user_detail_payroll_akomodasi	= 'AKOMODASI';
		$this->sys_user_detail_payroll_tunj_transport	= 'TUNJ_TRANSPORT';
		$this->sys_user_detail_payroll_komisi	= 'KOMISI';
		$this->sys_user_detail_payroll_tunj_level	= 'TUNJ_LEVEL';
		$this->sys_user_detail_payroll_tunj_jabatan	= 'TUNJ_JABATAN';
		$this->sys_user_detail_payroll_thp_leveling	= 'THP_LEVELING';
		$this->sys_user_detail_payroll_ot_moss	= 'OT_MOSS';
		$this->sys_user_detail_payroll_other_fee	= 'OTHER_FEE';
		$this->sys_user_detail_payroll_tunjangan_skill	= 'TUNJANGAN_SKILL';
		$this->sys_user_detail_payroll_lebih_hpemail	= 'LEBIH_HPEMAIL';
		$this->sys_user_detail_payroll_lebih_emailonly	= 'LEBIH_EMAILONLY';
		$this->sys_user_detail_payroll_lebih_rp	= 'LEBIH_RP';
		$this->sys_user_detail_payroll_tot_thp	= 'TOT_THP';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_agentid	= 'agentid';
		$this->f_bulan	= 'bulan';
		$this->f_hk	= 'hk';
		$this->f_kehadiran	= 'kehadiran';
		$this->f_contacted	= 'contacted';
		$this->f_verified	= 'verified';
		$this->f_reward	= 'reward';
		$this->f_pendidikan	= 'pendidikan';
		$this->f_foreign	= 'foreign';
		$this->f_score	= 'score';
		$this->f_level	= 'level';
		$this->f_akomodasi	= 'akomodasi';
		$this->f_tunj_transport	= 'tunj_transport';
		$this->f_komisi	= 'komisi';
		$this->f_tunj_level	= 'tunj_level';
		$this->f_tunj_jabatan	= 'tunj_jabatan';
		$this->f_thp_leveling	= 'thp_leveling';
		$this->f_ot_moss	= 'ot_moss';
		$this->f_other_fee	= 'other_fee';
		$this->f_tunjangan_skill	= 'tunjangan_skill';
		$this->f_lebih_hpemail	= 'lebih_hpemail';
		$this->f_lebih_emailonly	= 'lebih_emailonly';
		$this->f_lebih_rp	= 'lebih_rp';
		$this->f_tot_thp	= 'tot_thp';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->sys_user_detail_payroll_id,
			$this->f_agentid	=> $this->sys_user_detail_payroll_agentid,
			$this->f_bulan	=> $this->sys_user_detail_payroll_bulan,
			$this->f_hk	=> $this->sys_user_detail_payroll_hk,
			$this->f_kehadiran	=> $this->sys_user_detail_payroll_kehadiran,
			$this->f_contacted	=> $this->sys_user_detail_payroll_contacted,
			$this->f_verified	=> $this->sys_user_detail_payroll_verified,
			$this->f_reward	=> $this->sys_user_detail_payroll_reward,
			$this->f_pendidikan	=> $this->sys_user_detail_payroll_pendidikan,
			$this->f_foreign	=> $this->sys_user_detail_payroll_foreign,
			$this->f_score	=> $this->sys_user_detail_payroll_score,
			$this->f_level	=> $this->sys_user_detail_payroll_level,
			$this->f_akomodasi	=> $this->sys_user_detail_payroll_akomodasi,
			$this->f_tunj_transport	=> $this->sys_user_detail_payroll_tunj_transport,
			$this->f_komisi	=> $this->sys_user_detail_payroll_komisi,
			$this->f_tunj_level	=> $this->sys_user_detail_payroll_tunj_level,
			$this->f_tunj_jabatan	=> $this->sys_user_detail_payroll_tunj_jabatan,
			$this->f_thp_leveling	=> $this->sys_user_detail_payroll_thp_leveling,
			$this->f_ot_moss	=> $this->sys_user_detail_payroll_ot_moss,
			$this->f_other_fee	=> $this->sys_user_detail_payroll_other_fee,
			$this->f_tunjangan_skill	=> $this->sys_user_detail_payroll_tunjangan_skill,
			$this->f_lebih_hpemail	=> $this->sys_user_detail_payroll_lebih_hpemail,
			$this->f_lebih_emailonly	=> $this->sys_user_detail_payroll_lebih_emailonly,
			$this->f_lebih_rp	=> $this->sys_user_detail_payroll_lebih_rp,
			$this->f_tot_thp	=> $this->sys_user_detail_payroll_tot_thp,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-01-06 13:01:24 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

