<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Digital_channel_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->digital_channel_id	= 'ID';
		$this->digital_channel_channel	= 'CHANNEL';
		$this->digital_channel_template	= 'TEMPLATE';
		$this->digital_channel_konten_1	= 'KONTEN_1';
		$this->digital_channel_konten_2	= 'KONTEN_2';
		$this->digital_channel_konten_3	= 'KONTEN_3';
		$this->digital_channel_konten_4	= 'KONTEN_4';
		$this->digital_channel_konten_5	= 'KONTEN_5';
		$this->digital_channel_status	= 'STATUS';
		$this->digital_channel_last_update	= 'LAST_UPDATE';
		$this->digital_channel_userid	= 'USERID';
		$this->template_dc_id	= 'TEMPLATE_DC_ID';
		$this->template_dc_template	= 'TEMPLATE_DC_TEMPLATE';
		$this->template_dc_jumlah_konten	= 'JUMLAH_KONTEN';
		$this->template_dc_kode_template	= 'KODE_TEMPLATE';
		$this->statusna_id	= 'STATUSNA_ID';
		$this->statusna_status	= 'STATUSNA_STATUS';
		$this->userupdate_id	= 'USERUPDATE_ID';
		$this->userupdate_nmuser	= 'NMUSER';
		$this->userupdate_passuser	= 'PASSUSER';
		$this->userupdate_opt_level	= 'OPT_LEVEL';
		$this->userupdate_opt_status	= 'OPT_STATUS';
		$this->userupdate_picture	= 'PICTURE';
		$this->userupdate_nama	= 'NAMA';
		$this->userupdate_agentid	= 'AGENTID';
		$this->userupdate_kategori	= 'KATEGORI';
		$this->userupdate_tl	= 'TL';
		$this->userupdate_nik_absensi	= 'NIK_ABSENSI';
		$this->userupdate_agent_mos	= 'AGENT_MOS';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_channel	= 'channel';
		$this->f_template	= 'template';
		$this->f_konten_1	= 'konten_1';
		$this->f_konten_2	= 'konten_2';
		$this->f_konten_3	= 'konten_3';
		$this->f_konten_4	= 'konten_4';
		$this->f_konten_5	= 'konten_5';
		$this->f_status	= 'status';
		$this->f_last_update	= 'last_update';
		$this->f_userid	= 'userid';
		$this->f_template_dc_id	= 'template_dc_id';
		$this->f_template_dc_template	= 'template_dc_template';
		$this->f_jumlah_konten	= 'jumlah_konten';
		$this->f_kode_template	= 'kode_template';
		$this->f_statusna_id	= 'statusna_id';
		$this->f_statusna_status	= 'statusna_status';
		$this->f_userupdate_id	= 'userupdate_id';
		$this->f_nmuser	= 'nmuser';
		$this->f_passuser	= 'passuser';
		$this->f_opt_level	= 'opt_level';
		$this->f_opt_status	= 'opt_status';
		$this->f_picture	= 'picture';
		$this->f_nama	= 'nama';
		$this->f_agentid	= 'agentid';
		$this->f_kategori	= 'kategori';
		$this->f_tl	= 'tl';
		$this->f_nik_absensi	= 'nik_absensi';
		$this->f_agent_mos	= 'agent_mos';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->digital_channel_id,
			$this->f_channel	=> $this->digital_channel_channel,
			$this->f_template	=> $this->digital_channel_template,
			$this->f_konten_1	=> $this->digital_channel_konten_1,
			$this->f_konten_2	=> $this->digital_channel_konten_2,
			$this->f_konten_3	=> $this->digital_channel_konten_3,
			$this->f_konten_4	=> $this->digital_channel_konten_4,
			$this->f_konten_5	=> $this->digital_channel_konten_5,
			$this->f_status	=> $this->digital_channel_status,
			$this->f_last_update	=> $this->digital_channel_last_update,
			$this->f_userid	=> $this->digital_channel_userid,
			$this->f_template_dc_id	=> $this->template_dc_id,
			$this->f_template_dc_template	=> $this->template_dc_template,
			$this->f_jumlah_konten	=> $this->template_dc_jumlah_konten,
			$this->f_kode_template	=> $this->template_dc_kode_template,
			$this->f_statusna_id	=> $this->statusna_id,
			$this->f_statusna_status	=> $this->statusna_status,
			$this->f_userupdate_id	=> $this->userupdate_id,
			$this->f_nmuser	=> $this->userupdate_nmuser,
			$this->f_passuser	=> $this->userupdate_passuser,
			$this->f_opt_level	=> $this->userupdate_opt_level,
			$this->f_opt_status	=> $this->userupdate_opt_status,
			$this->f_picture	=> $this->userupdate_picture,
			$this->f_nama	=> $this->userupdate_nama,
			$this->f_agentid	=> $this->userupdate_agentid,
			$this->f_kategori	=> $this->userupdate_kategori,
			$this->f_tl	=> $this->userupdate_tl,
			$this->f_nik_absensi	=> $this->userupdate_nik_absensi,
			$this->f_agent_mos	=> $this->userupdate_agent_mos,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-12-15 07:45:24 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

