<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_pembinaan_nonq_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->t_pembinaan_konseling_id	= 'ID';
		$this->t_pembinaan_konseling_nama_konseling	= 'NAMA_KONSELING';
		$this->t_pembinaan_konseling_konselor	= 'KONSELOR';
		$this->t_pembinaan_konseling_bulan_tahun	= 'BULAN_TAHUN';
		$this->t_pembinaan_konseling_data_performance	= 'DATA_PERFORMANCE';
		$this->t_pembinaan_konseling_ketidaksesuaian	= 'KETIDAKSESUAIAN';
		$this->t_pembinaan_konseling_jenis_pembinaan	= 'JENIS_PEMBINAAN';
		$this->t_pembinaan_konseling_komitmen_perbaikan	= 'KOMITMEN_PERBAIKAN';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_nama_konseling	= 'nama_konseling';
		$this->f_konselor	= 'konselor';
		$this->f_bulan_tahun	= 'bulan_tahun';
		$this->f_data_performance	= 'data_performance';
		$this->f_ketidaksesuaian	= 'ketidaksesuaian';
		$this->f_jenis_pembinaan	= 'jenis_pembinaan';
		$this->f_komitmen_perbaikan	= 'komitmen_perbaikan';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->t_pembinaan_konseling_id,
			$this->f_nama_konseling	=> $this->t_pembinaan_konseling_nama_konseling,
			$this->f_konselor	=> $this->t_pembinaan_konseling_konselor,
			$this->f_bulan_tahun	=> $this->t_pembinaan_konseling_bulan_tahun,
			$this->f_data_performance	=> $this->t_pembinaan_konseling_data_performance,
			$this->f_ketidaksesuaian	=> $this->t_pembinaan_konseling_ketidaksesuaian,
			$this->f_jenis_pembinaan	=> $this->t_pembinaan_konseling_jenis_pembinaan,
			$this->f_komitmen_perbaikan	=> $this->t_pembinaan_konseling_komitmen_perbaikan,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-03-02 14:02:28 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

