<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_log_problem_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->t_log_problem_id	= 'ID';
		$this->t_log_problem_tanggal	= 'TANGGAL';
		$this->t_log_problem_agentid	= 'AGENTID';
		$this->t_log_problem_kategori_gangguan	= 'KATEGORI_GANGGUAN';
		$this->t_log_problem_solusi	= 'SOLUSI';
		$this->t_log_problem_status	= 'STATUS';
		$this->t_log_problem_keterangan	= 'KETERANGAN';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_tanggal	= 'tanggal';
		$this->f_agentid	= 'agentid';
		$this->f_kategori_gangguan	= 'kategori_gangguan';
		$this->f_solusi	= 'solusi';
		$this->f_status	= 'status';
		$this->f_keterangan	= 'keterangan';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->t_log_problem_id,
			$this->f_tanggal	=> $this->t_log_problem_tanggal,
			$this->f_agentid	=> $this->t_log_problem_agentid,
			$this->f_kategori_gangguan	=> $this->t_log_problem_kategori_gangguan,
			$this->f_solusi	=> $this->t_log_problem_solusi,
			$this->f_status	=> $this->t_log_problem_status,
			$this->f_keterangan	=> $this->t_log_problem_keterangan,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-11-09 08:35:30 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

