<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class News_config
{

	function __construct()
	{
		/* title */
		$this->general		= new General_title();
		$this->news_id	= 'ID';
		$this->news_idsender	= 'ID SENDER';
		$this->optlevel_receiver	= 'RECEIVER';
		$this->news_title = 'TITLE';
		$this->news_kategori	= 'KATEGORI NEWS';
		$this->news_isiberita	= 'ISI BERITA';
		$this->news_tanggalpublish	= 'TANGGAL PUBLISH';
		$this->news_statuspublish	= 'STATUS PUBLISH';




		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_id_sender	= 'id_sender';
		$this->f_optlevel_receiver	= 'optlevel_receiver';
		$this->f_title	= 'title';
		$this->f_kategori_news	= 'kategori_news';
		$this->f_isi_berita	= 'isi_berita';
		$this->f_tanggal_publish	= 'tanggal_publish';
		$this->f_status_publish	= 'status_publish';




		/* CONFIG FORM LIST */
		/* field_alias_database => $title */
		$this->table_column = array(
			$this->f_id	=> $this->news_id,
			$this->f_id_sender	=> $this->news_idsender,
			$this->f_optlevel_receiver	=> $this->optlevel_receiver,
			$this->f_title	=> $this->news_title,
			$this->f_kategori_news	=> $this->news_kategori,
			$this->f_isi_berita	=> $this->news_isiberita,
			$this->f_tanggal_publish	=> $this->news_tanggalpublish,
			$this->f_status_publish	=> $this->news_statuspublish,

		);
	}
};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-01-31 15:28:46 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
